version: '2'
services:
  login_app:
      image: node:9.11.1-alpine
      env_file: [./dev.env]
      environment: [VIRTUAL_HOST=login_app.dev.local]
      expose: ["3000"]
      ports: ["3000:3000"]
      volumes: [".:/app"]
      working_dir: /app
      command: npm run build
      network_mode: bridge
